sigprae/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    #path('user/',include('usersystem.urls')),

    #path('terms/', include('termsandconditions.urls')),
    
    path('interestarea/',include('apps.interestarea.urls')),

    path('subject/',include('apps.subject.urls')),
    
    path('api-auth/', include('rest_framework.urls')),
]

usersystem/urls.py
from django.contrib import admin
from django.urls import path

from .views import *
app_name = 'user'
urlpatterns = [
    path('test/', render_test,name="render_test"),
    path('user-form/', user_form_test,name="user_form_test"),
    path('user-list/', user_list,name="user_list"),
    path('', render_base,name="render_base"),
    path('register_theo/', register_theo,name='register_theo'),
    path('login_theo/', login_theo,name='login_theo'),
    path('mateus/1', render_login,name="render_login"),
    path('mateus/', render_register,name="render_register"),
]

from django.conf.urls.static import static
from django.conf import settings
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

usersystem/models.py
from unicodedata import category
from django.db import models

from django.contrib.auth.models import AbstractUser
import uuid


class User(AbstractUser):
    USER_PROFESSOR = 'UP'
    USER_WORKER = 'UW'
    USER_STUDENT = 'US'
    USER_COMMUNITY = 'UC'
    #Professor, Student, Worker, Administrator, Community
    USER_PROFILE = (
        (USER_PROFESSOR,'Professor'),
        (USER_WORKER,'Técnico Administrativo'),
        (USER_STUDENT,'Estudante'),
        (USER_COMMUNITY,'Membro da Comunidade')
    )

    GENRE_MALE = 'M'
    GENRE_FEMALE = 'F'
    GENRE_NULL = 'O'

    USER_GENRE = (
        (GENRE_MALE,'Masculino'),
        (GENRE_FEMALE,'Feminino'),
        (GENRE_NULL,'Não Informado')
    )

    full_name = models.CharField(max_length=100, blank=True,null=True)
    birth_date = models.DateField(null=True, blank=True)
    phone_number = models.CharField(max_length=11, blank=True,null=True) #86999494681

    profile = models.CharField('Perfil', max_length=2,choices=USER_PROFILE,blank=True,null=True)
    genre = models.CharField('Gênero', max_length=1,choices=USER_GENRE,default=GENRE_NULL)
    cpf  = models.CharField(max_length=11, blank=True,null=True)
    slug = models.SlugField(max_length=150,unique=True,default="page-slug")

    class Meta:
        verbose_name = 'Usuário'
        verbose_name_plural = 'Usuários'
        ordering = ['-full_name']

    def __str__(self):
        return self.full_name if (self.full_name) else self.username

    def save(self, *args, **kwargs):
        if not self.id:
            self.slug = uuid.uuid4()
        super(User, self).save(*args, **kwargs)

    @property
    def has_active_term(self):
        return self.userterms.all().exists()

    @property
    def get_active_term(self):
        if(self.has_active_term):
            return self.userterms.all().last().terms
        return None


    @staticmethod
    def validate_age(birth_date,today_date):
        '''
            brith_date e today_date tem o formado AAAA-MM-DD
        '''
        from datetime import datetime
        #https://docs.python.org/3/library/datetime.html#strftime-strptime-behavior
        new_birth_date = datetime.strptime(birth_date, '%Y-%m-%d')
        new_today_date = datetime.strptime(today_date, '%Y-%m-%d')
        diff = new_today_date - new_birth_date
        years = diff.days // 365
        if(years >= 18):
            return True
        else:
            return False

    @staticmethod
    def register(username,birth,full_name,password):
        if(len(username) < 5):
            return False
        if(len(birth)==10):
            import re
            expression = "^\d{4}-(0[1-9]|1[0-2])-(0[1-9]|[12][0-9]|3[01])$"
            match = re.search(expression, birth)
            if not match:
                return False
        else:
            return False

        if(len(full_name)<5):
            return False

        if not (len(password)>=8):
            return False
        
        if (User.objects.filter(username=username).exists()):
            return False

        User.objects.create(username=username, password=password,full_name=full_name,birth_date=birth)
        
        return True

    @staticmethod
    def check_student_email(email):
        import re
        match = re.search("@aluno\.uespi\.br", email)
        return True if (match) else False

    @staticmethod
    def check_professor_email(email):
        import re
        match = re.search("@[^(aluno)].*\.uespi\.br", email)
        return True if (match) else False

    @staticmethod
    def check_worker_email(email):
        import re
        match = re.search("@uespi\.br", email)
        return True if (match) else False

usersystem/forms.py
from django import forms
from usersystem.models import User

from django.core.exceptions import ValidationError

from datetime import datetime

from validate_docbr import CPF

class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ["username",'password', "email",'full_name','cpf','genre','birth_date','profile','phone_number']

    password=forms.CharField(label="Senha",widget=forms.PasswordInput())
    confirm_password=forms.CharField(widget=forms.PasswordInput())

    def clean_confirm_password(self):
        data_password = self.cleaned_data['password']
        data_confirm_password = self.cleaned_data['confirm_password']
        if not data_password == data_confirm_password:
            raise ValidationError("Confirmação de senha não confere.")

        return data_confirm_password

    def clean_birth_date(self):
        data_birth_date = self.cleaned_data['birth_date']
        data_today = datetime.today().strftime("%Y-%m-%d")
        if not (User.validate_age(data_birth_date.strftime("%Y-%m-%d"),data_today)):
            raise ValidationError("Você não é maior de idade.")

        return data_birth_date




#Referência útil
#https://docs.djangoproject.com/en/4.0/ref/forms/fields/
class UserEssentialForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ["username","password",'profile',"email",'full_name','cpf','birth_date']
        help_texts = {
            'birth_date' : 'Formato: dd/mm/aaaa',
        }
        labels = {
            "profile": "Perfil",
            "cpf": "CPF",
            "full_name": "Nome completo",
            "birth_date": "Data de nascimento"
        }
        widgets = {
            'cpf': forms.TextInput(attrs={'class':'form-control'}),
        } 
    password=forms.CharField(label="Senha",widget=forms.PasswordInput())
    confirm_password=forms.CharField(label="Confirme sua Senha",widget=forms.PasswordInput())

    terms_and_conditions = forms.BooleanField(label="Aceita os termos?",required=False)


    def __init__(self, *args, **kwargs):
        super(UserEssentialForm, self).__init__(*args, **kwargs)
        self.fields['username'].widget.attrs['placeholder'] = 'Username'
        self.fields['email'].widget.attrs['placeholder'] = 'Digite seu E-mail'
        self.fields['full_name'].widget.attrs['placeholder'] = 'Digite seu Nome Completo'
        self.fields['cpf'].widget.attrs['placeholder'] = 'Digite seu CPF'
        self.fields['birth_date'].widget.attrs['placeholder'] = 'Data de Nascimento'
        self.fields['password'].widget.attrs['placeholder'] = 'Digite a Senha'
        self.fields['confirm_password'].widget.attrs['placeholder'] = 'Confirme a Senha'
        

   
    # - verificar confirmação de senha
    def clean_confirm_password(self):
        data_password = self.cleaned_data['password']
        data_confirm_password = self.cleaned_data['confirm_password']
        if not data_password == data_confirm_password:
            raise ValidationError("Confirmação de senha não confere.")

        return data_confirm_password
    
    # - verificar maior de idade
    def clean_birth_date(self):
        data_birth_date = self.cleaned_data['birth_date']
        if not data_birth_date:
            raise ValidationError("Você não inseriu sua data de nascimento.")
        data_today = datetime.today().strftime("%Y-%m-%d")
        if not (User.validate_age(data_birth_date.strftime("%Y-%m-%d"),data_today)):
            raise ValidationError("Você não é maior de idade.")

        return data_birth_date

    # - verificar email e profile
    def clean_email(self):
        data_email = self.cleaned_data['email']
        data_profile = self.cleaned_data['profile']
        if (data_profile == User.USER_PROFESSOR) and (not User.check_professor_email(data_email)): 
            raise ValidationError("Não foi colocado e-mail de Professor Institucional.")
        elif (data_profile == User.USER_STUDENT) and (not User.check_student_email(data_email)):
            raise ValidationError("Não foi colocado e-mail de Aluno Institucional.")
        elif (data_profile == User.USER_COMMUNITY):
            if User.check_professor_email(data_email):
                raise ValidationError("Você inseriu um e-mail de Professor Institucional.")
            elif User.check_student_email(data_email):
                raise ValidationError("Você inseriu um e-mail de Estudante Institucional.")
            elif User.check_worker_email(data_email):
                raise ValidationError("Você inseriu um e-mail de Técnico Administrativo Institucional.")
        if (data_profile == User.USER_WORKER) and (not User.check_worker_email(data_email)):
            raise ValidationError("Não foi colocado e-mail de Técnico Administrativo Institucional.")

        return data_email
        

    def clean_cpf(self):
        data_cpf = self.cleaned_data['cpf']
        if not data_cpf:
            raise ValidationError("Você não inseriu o CPF.")
        cpf = CPF()
        if not cpf.validate(data_cpf):
            raise ValidationError("Você inseriu um CPF inválido.")
        
        if User.objects.filter(cpf=data_cpf).exists():
            raise ValidationError("Um usuário com este CPF já está cadastrado.")

        return data_cpf

    # - verificar se marcou o termo de consentimento
    def clean_terms_and_conditions(self):
        data_terms = self.cleaned_data['terms_and_conditions']
        if not data_terms:
            raise ValidationError("Você precisa concordar com os Termos e Condições.")

        return data_terms

usersystem/views.py
from django.shortcuts import render,redirect
from usersystem.forms import UserEssentialForm
from usersystem.models import User
from django.urls import reverse
from termsandconditions.models import UserTermsAndConditions, TermsAndConditions

# Create your views here.

def render_test(request):
    from datetime import datetime
    today = datetime.now()
    user = "Mateus"
    data = {
        'datetime':today,
        'other':user
    }
    return render(request,"usersystem/test.html",context=data)

def user_list(request):
    users = User.objects.filter(is_superuser=False,is_staff=False)
    return render(request,"usersystem/user_list.html",context={'users':users})


def user_form_test(request):
    if request.method == 'POST':
        userform = UserEssentialForm(request.POST)
        if userform.is_valid():
            new_user = userform.save(commit=False)
            new_user.save()
            #associar ao termo de referência vigente
            return redirect(reverse('user:user_list'))
    else:
         userform = UserEssentialForm()
    return render(request,"usersystem/user_form.html",context={'form':userform})


def render_base(request):
    return render(request,"base.html")
    
    
def register_theo(request):
    if request.method == 'POST':
        user_form = UserEssentialForm(request.POST)
        if user_form.is_valid():
            new_user = user_form.save(commit=False)
            new_user.save()
            #associar ao termo de referência vigente
            return redirect(reverse('user:login_theo'))
    else:
        user_form = UserEssentialForm()
    return render(request,"usersystem/register_theo.html", context={'form': user_form})

def login_theo(request):
    return render(request,"usersystem/login_theo.html")


def render_login(request):
    return render(request,"usersystem/mateus/login.html")


def render_register(request):
    #return render(request,"usersystem/mateus/register.html")
    if request.method == 'POST':
        userform = UserEssentialForm(request.POST)
        if userform.is_valid():
            new_user = userform.save(commit=False)
            new_user.save()
            #associar ao termo de referência vigente
            if(TermsAndConditions.get_active()):
                UserTermsAndConditions.objects.create(
                    user = new_user,
                    terms = TermsAndConditions.get_active()
                )
            return redirect(reverse('user:user_list'))
    else:
        userform = UserEssentialForm()
    return render(request,"usersystem/mateus/register_form_django.html",context={'form':userform})

usersystem/templates/usersystem/login_theo.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
    <link rel="stylesheet" href="{% static 'usersystem/theo_custom.css'%}"> 
   <script src="https://kit.fontawesome.com/d40a2657b6.js" crossorigin="anonymous"></script>
    <!-- Poder usar icons do fontawesome -->
</head>

<body>
    <div class="container">
        <div class="content second-content">
            <div class="first-column">
                <h2 class="title title-primary">Bem vindo ao</h2>
                <h3 class="subtitle subtitle-primary">SIGPRAE</h3>
                <p class="description description-primary">Novo por aqui? Insira seus dados pessoais</p>
                <p class="description description-primary">e comece a jornada conosco</p>
                <a href="{% url 'user:register_theo' %}"></a><button class="btn btn-primary">Cadastrar</button>
            </div> <!--End first-column-->
            <div class="second-column">
                <h2 class="title title-second">Iniciar sessão no sistema</h2>
                <div class="social-media">
                    <ul class="list-social-media"> <!--ul>li*3>a-->
                        <a class="link-social-media" href="#">
                            <li class="item-social-media">
                                <i class="fa-brands fa-facebook-f"></i>
                            </li>
                        </a>
                        <a class="link-social-media" href="#">
                            <li class="item-social-media">
                                <i class="fa-brands fa-google-plus-g"></i>
                            </li>
                        </a>
                        <a class="link-social-media" href="#">
                            <li class="item-social-media">
                                <i class="fa-brands fa-linkedin-in"></i>
                            </li>
                        </a> 
                    </ul> <!--End list-social-media-->
                </div> <!--End social media-->
                <p class="description-second">ou use seu e-mail para entrar:</p>
                <form class="form">
                    <label class="label-input" for="">
                        <i class="fa-solid fa-envelope icon-modify"></i>
                        <input type="email", placeholder="E-mail">
                    </label>
                    <label class="label-input" for="">
                        <i class="fa-solid fa-lock icon-modify"></i>
                        <input type="password", placeholder="Senha">
                    </label>
                    <a class="password" href="#">esqueceu sua senha?</a>
                    <button class="btn btn-second">Entrar</button>
                </form> <!--End form-->
            </div> <!--End second-column-->
        </div> <!--End content second-content-->
    </div> <!--End container-->
</body>

</html>

usersystem/templates/usersystem/register_theo.html
{% load static %}

<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
    <link rel="stylesheet" href="{% static 'usersystem/theo_custom.css'%}"> 
   <script src="https://kit.fontawesome.com/d40a2657b6.js" crossorigin="anonymous"></script>
    <!-- Poder usar icons do fontawesome -->
</head>

<body>
    <div class="container">
        <div class="content first-content">
            <div class="first-column">
                <h2 class="title title-primary">Bem vindo ao</h2>
                <h3 class="subtitle subtitle-primary">SIGPRAE</h3>
                <p class="description description-primary">Já tem uma conta?</p>
                <p class="description description-primary">Faça login com seus dados</p>
                <a href="{% url 'user:login_theo' %}"><button class="btn btn-primary" type="submit">Entrar</button></a>
            </div> <!--End first-column-->
            <div class="second-column">
                <h2 class=" title title-second">Realizar cadastro</h2>
                <div class="social-media">
                    <ul class="list-social-media"> <!--ul>li*3>a-->
                        <a class="link-social-media" href="#">
                            <li class="item-social-media">
                                <i class="fa-brands fa-facebook-f"></i>
                            </li>
                        </a>
                        <a class="link-social-media" href="#">
                            <li class="item-social-media">
                                <i class="fa-brands fa-google-plus-g"></i>
                            </li>
                        </a>
                        <a class="link-social-media" href="#">
                            <li class="item-social-media">
                                <i class="fa-brands fa-linkedin-in"></i>
                            </li>
                        </a> 
                    </ul> <!--End list-social-media-->
                </div> <!--End social media-->
                <p class="description-second">ou use seus dados para cadastrar:</p>
                
                
                <form  action="{% url 'user:register_theo' %}" method="post">
                    {% csrf_token %}
                    {{ form.username }} <small>{{ form.username.help_text }}</small>
                   <!--<table> 
                        {{ form.as_table }}
                    </table>-->
                    <button class="btn btn-second" type="submit">Cadastrar</button>
                </form>


                <!----<form class="form">
                    <label class="label-input" for="">
                        <i class="fa-solid fa-user icon-modify"></i>
                        <input type="email", placeholder="E-mail">
                    </label>
                    <label class="label-input" for="">
                        <i class="fa-solid fa-envelope icon-modify"></i>
                        <input type="email", placeholder="E-mail">
                    </label>
                    <label class="label-input" for="">
                        <i class="fa-solid fa-lock icon-modify"></i>
                        <input type="password", placeholder="Senha">
                    </label>
                    <a class="password" href="#">esqueceu sua senha?</a>
                    <button class="btn btn-second">Entrar</button>
                </form> End form-->
            </div> <!--End second-column-->

        </div> <!--End content first-content-->

        <div class="content second-content">

            <div class="first-column">
                <h2 class="title title-primary">Bem vindo ao</h2>
                <h3 class="subtitle subtitle-primary">SIGPRAE</h3>
                <p class="description description-primary">Novo por aqui? Insira seus dados pessoais</p>
                <p class="description description-primary">e comece a jornada conosco</p>
                <button class="btn btn-primary">Cadastrar</button>
            </div> <!--End first-column-->
            <div class="second-column">
                <h2 class="title title-second">Iniciar sessão no sistema</h2>
                <div class="social-media">
                    <ul class="list-social-media"> <!--ul>li*3>a-->
                        <a class="link-social-media" href="#">
                            <li class="item-social-media">
                                <i class="fa-brands fa-facebook-f"></i>
                            </li>
                        </a>
                        <a class="link-social-media" href="#">
                            <li class="item-social-media">
                                <i class="fa-brands fa-google-plus-g"></i>
                            </li>
                        </a>
                        <a class="link-social-media" href="#">
                            <li class="item-social-media">
                                <i class="fa-brands fa-linkedin-in"></i>
                            </li>
                        </a> 
                    </ul> <!--End list-social-media-->
                </div> <!--End social media-->
                <p class="description-second">ou use seu e-mail para entrar:</p>
                <form class="form">
                    <label class="label-input" for="">
                        <i class="fa-solid fa-envelope icon-modify"></i>
                        <input type="email", placeholder="E-mail">
                    </label>
                    <label class="label-input" for="">
                        <i class="fa-solid fa-lock icon-modify"></i>
                        <input type="password", placeholder="Senha">
                    </label>
                    <a class="password" href="#">esqueceu sua senha?</a>
                    <button class="btn btn-second">Entrar</button>
                </form> <!--End form-->
            </div> <!--End second-column-->








            













        </div> <!--End content second-content-->
    </div> <!--End container-->
</body>

</html>

usersystem/templates/usersystem/test.html
{% extends "base.html" %}

{% block title%}Página Inicial{% endblock %}

{% block column_1%}Cursos em Aberto{% endblock %}

{% block column_2%}Cursos em Andamento{% endblock %}

{% block column_3%}Cursos Encerrados{% endblock %}

usersystem/templates/usersystem/user_form.html
<style>
    .form-control{
        color: red;
    }
</style>

<a href="{% url 'user:user_list' %}">Listar Usuários</a>


<form action="{% url 'user:user_form_test' %}" method="post">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>
    <input type="submit" value="Submit">
</form>

usersystem/templates/usersystem/user_list.html
<a href="{% url 'user:user_form_test' %}">Cadastrar Usuário</a>
<br>
{% if not users %}
<b>Não existem usuários cadastrados.</b>
{% else %}
    <table>
        <tr>
            <th>Nome</th>
            <th>Perfil</th>
            <th>Criação</th>
        </tr>
    {% for one_user in users %}
        <tr>
            <td>{{ one_user.full_name|upper }}</td>
            <td>{{ one_user.get_profile_display|upper }}</td>
            <td>{{ one_user.date_joined|date:"d/m/Y H:i:s" }}</td>
        </tr>
    {% endfor %}
    </table>
{% endif %}